name: RemoteAuth
version: '${project.version}'
main: com.rossijr.remoteauth.RemoteAuth
api-version: '1.17'
commands:
  login:
    description: Login to the server
    usage: /<command> <password>
  register:
      description: Register to the server
      usage: /<command> <password> <password>
  changepassword:
    description: Change your password
    usage: /<command> <newpassword>
  rasetspawn:
    description: Set the spawn point
    usage: /<command>
    permission: remoteauth.setspawn
settings:
  commands:
    log: false