package com.rossijr.remoteauth.authentication.models;

import com.rossijr.remoteauth.db.annotations.ColumnType;
import com.rossijr.remoteauth.db.annotations.model_annotation.Column;
import com.rossijr.remoteauth.db.annotations.model_annotation.Id;
import com.rossijr.remoteauth.db.annotations.model_annotation.Table;

import java.util.UUID;

/**
 * UserModel class to represent the user in the database and in the application
 */
@Table(key = "db.user_table")
public class UserModel {
    @Id(autoGenerated = false) @Column(type = ColumnType.UUID)
    private UUID uuid;
    @Column(key = "db.username_column")
    private String username;
    @Column(key = "db.password_column")
    private String password;

    public UserModel(){
    }


    public UserModel(UUID uuid, String username, String password) {
        this.uuid = uuid;
        this.username = username;
        this.password = password;
    }

    public UserModel(UUID uuid, String username) {
        this.uuid = uuid;
        this.username = username;
    }

    public UUID getUuid() {
        return uuid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "UserModel{" +
                "uuid=" + uuid +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}
